name="Oleg"
age=16
km=12.4
my_favorite_games=[RDR2,GTA5,FS22]
my_shortcomings=[]
student=true
schoolboy=false
shopping=(potatoes,meat,juice)
my_favorite_cars={CLS63amg,M5f90,PORSHE911}
pets={"1":"dog","2":"cat"}
print(name,type(name))
print(age,type(age))
print(km,type(km))
print(my_favorite_games,type(my_favorite_games))
print(my_shortcomings,type(my_shortcoming))
print(student,type(student))
print(schoolboy,type(schoolboy))
print(shopping,type(sopping))
print(my_favorite_cars,type(my_favorite_cars))
print(pets,type(pets))
